apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb-private
spec:
  # Configures the IngressClass to use EKS Auto Mode
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: alb-private
